		(() => {
			FWDRLS3DUtils.onReady(function(){
				var coverflow = new FWDSimple3DCoverflow({
					
					//required settings
					coverflowHolderDivId:"coverflowDiv",
        			coverflowDataListDivId:"coverflowBlock",
        			displayType:"responsive",
        			coverflowWidth:5000,
        			coverflowOffsetHeight:140,
        			mainFolderPath:"https://cdn.jsdelivr.net/gh/Magmavox/covid-expo/load",
        			skinPath:"skin_black",
        			initializeOnlyWhenVisible:"no",
												
					//main settings
					backgroundColor:"#112530",
					backgroundImagePath:"",
					backgroundSize:"auto",
					backgroundPosition:"center",
					backgroundRepeat:"repeat",
					coverflowStartPosition:"left",
					coverflowTopology:"flipping",
					coverflowXRotation:0,
					coverflowYRotation:30,
					numberOfThumbnailsToDisplayLeftAndRight:"all",
					infiniteLoop:"no",
					rightClickContextMenu:"developer",
					useDragAndSwipe:"yes",
					fluidWidthZIndex:1000,
					preloaderbackgroundColor:"#1d1d1d",
					preloaderFillColor:"#E4E4E4",
					
					//thumbnails settings
					useDefaultThumbnailsWidthAndHeight:"no",
					thumbnailWidth:500,
					thumbnailHeight:329,
					thumbnailMaxHeight:500,
					thumbnailResizeOffest:100,
					textMaxWidth:530,
					thumbnailXOffset3D:86,
					thumbnailXSpace3D:78,
					thumbnailZOffset3D:200,
					thumbnailZSpace3D:93,
					thumbnailYAngle3D:70,
					thumbnailHoverOffset:0,
					thumbnailBorderSize:0,
					thumbnailOffsetY:0,
					thumbnailBackgroundColor:"#4a4a4a",
					thumbnailBorderColor1:"#FFFFFF",
					thumbnailBorderColor2:"#FFFFFF",
					transparentImages:"no",
					thumbnailsAlignment:"bottom",
					maxNumberOfThumbnailsOnMobile:20,
					showThumbnailsGradient:"no",
					thumbnailGradientColor1:"rgba(29, 29, 29, 0)",
					thumbnailGradientColor2:"rgba(29, 29, 29, 1)",
					showText:"yes",
					textOffset:10,
					showThumbnailBoxShadow:"yes",
					thumbnailBoxShadowCss:"0px 2px 2px #1d1d1d",
					reflectionHeight:50,
					reflectionDistance:0,
					reflectionOpacity:.2,
										
					//controls settings
					slideshowDelay:5000,
					autoplay:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					controlsMaxWidth:530,
					controlsPosition:"bottom",
					controlsOffset:-23,
					showLargeNextAndPrevCoverflowButtons:"no",
					largeNextAndPrevButtonsOffest:20,
					largeNextAndPrevButtonsMaxWidthPos:0,
					showNextAndPrevCoverflowButtons:"yes",
					nextAndPrevCoverflowButtonsOffsetX:27,
					showSlideshowButton:"yes",
					slideshowPreloaderBackgroundColor:"#333333",
					slideshowpreloaderFillColor:"#E4E4E4",
					showScrollbar:"yes",
					showBulletsNavigation:"no",
					bulletsNormalColor:"#999999",
					bulletsSelectedColor:"#000000",
					bulletsNormalRadius:5,
					bulletsSelectedRadius:8,
					spaceBetweenBullets:10,
					bulletsOffset:28,
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"no",
					scrollbarHandlerWidth:200,
					scrollbarTextColorNormal:"#E4E4E4",
					scrollbarTextColorSelected:"#000000",
					addKeyboardSupport:"yes",
					
				});
			});
		})();
